from weather import data

class Forecast:
    def __init__(self, data):
        self.conditions_1 = data['forecast']['simpleforecast'][0]['conditions']
        self.high_1 = data['forecast']['simpleforecast'][0]['high']
        self.low_1 = data['forecast']['simpleforecast'][0]['low']
        self.conditions_2 = data['forecast']['simpleforecast'][1]['conditions']
        self.high_2 = data['forecast']['simpleforecast'][1]['high']
        self.low_2 = data['forecast']['simpleforecast'][1]['low']
        self.conditions_3 = data['forecast']['simpleforecast'][2]['conditions']
        self.high_3 = data['forecast']['simpleforecast'][2]['high']
        self.low_3 = data['forecast']['simpleforecast'][2]['low']
        self.conditions_4 = data['forecast']['simpleforecast'][3]['conditions']
        self.high_4 = data['forecast']['simpleforecast'][3]['high']
        self.low_4 = data['forecast']['simpleforecast'][3]['low']
        self.conditions_5 = data['forecast']['simpleforecast'][4]['conditions']
        self.high_5 = data['forecast']['simpleforecast'][4]['high']
        self.low_5 = data['forecast']['simpleforecast'][4]['low']
        self.conditions_6 = data['forecast']['simpleforecast'][5]['conditions']
        self.high_6 = data['forecast']['simpleforecast'][5]['high']
        self.low_6 = data['forecast']['simpleforecast'][5]['low']
        self.conditions_7 = data['forecast']['simpleforecast'][6]['conditions']
        self.high_7 = data['forecast']['simpleforecast'][6]['high']
        self.low_7 = data['forecast']['simpleforecast'][6]['low']
        self.conditions_8 = data['forecast']['simpleforecast'][7]['conditions']
        self.high_8 = data['forecast']['simpleforecast'][7]['high']
        self.low_8 = data['forecast']['simpleforecast'][7]['low']
        self.conditions_9 = data['forecast']['simpleforecast'][8]['conditions']
        self.high_9 = data['forecast']['simpleforecast'][8]['high']
        self.low_9 = data['forecast']['simpleforecast'][8]['low']
        self.conditions_10 = data['forecast']['simpleforecast'][9]['conditions']
        self.high_10 = data['forecast']['simpleforecast'][9]['high']
        self.low_10 = data['forecast']['simpleforecast'][9]['low']
